# Validation set evaluation metrics:
# Top-1 Accuracy: 99.2%
# Top-5 Accuracy: 100.0%
seed: null
environment:
    platform: local
    cuda:
        cudnn_deterministic: true
        cudnn_benchmark: false
data:
    dataset_path: data/mnist/
    train_batch_size: 64
    test_batch_size: 5000
    workers: 4
model:
    architecture: lenet5
    loss: nll_loss
    arch_config:
        moving_average_mode: 'off'
        moving_average_momentum: 0.99
        x_quant: gf-2
        w_quant: ls-1
        clamp:
            kind: identity
        conv1_filters: 20
        conv2_filters: 50
        output_classes: 10
optimization:
    epochs: 10
    optimizer:
        algorithm: adadelta
        lr: 1.0
    lr_scheduler:
        scheduler: step_lr
        step_size: 1
        gamma: 0.7
log:
    level: INFO
    interval: 10
    tensorboard: true
    tensorboard_root: runs/
    root_experiments_dir: experiments/
    save_model_freq: 2
